#!/usr/bin/env python3
"""Exercise the real Fizeau boot parser against SwitchColor serialization.

Run after scripts/prepare_backend.py. On Windows, pass --bash with devkitPro's
MSYS2 bash.exe; on other hosts gcc/g++ are used directly. Generated sources and
binaries stay under build/backend-boot-test. No Switch hardware is required.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "build/backend-boot-test"
UPSTREAM = ROOT / "third_party/fizeau"
PATCHED = ROOT / "build/fizeau-backend"
FINAL_MARKER = "if (auto res = ini_parse_stream(reader, &read_ctx, fz::Config::ini_handler, &config); !res)"


def balanced_block(text: str, marker: str) -> str:
    """Extract one exact production brace block, failing if its anchor changes."""
    if text.count(marker) != 1:
        raise RuntimeError(f"Expected one production anchor: {marker}")
    start = text.index(marker)
    opening = text.index("{", start)
    depth = 0
    for position in range(opening, len(text)):
        if text[position] == "{":
            depth += 1
        elif text[position] == "}":
            depth -= 1
            if not depth:
                return text[start : position + 1]
    raise RuntimeError(f"Unclosed production block: {marker}")


def boot_function(source: str, name: str) -> str:
    callback = balanced_block(source, "config.parse_profile_switch_action =") + ";"
    # This includes the exact production file-read context and fgets-style
    # reader. The only replacement is fsFileRead's host byte-buffer transport.
    context_start = source.index("    struct FileReadContext {")
    config_start = source.index("    fz::Config config;", context_start)
    read_context = source[context_start:config_start]
    reader = balanced_block(source, "ini_reader reader =") + ";"
    final = balanced_block(source, FINAL_MARKER)
    return f"""
sc::Snapshot {name}(const std::string& text) {{
    context = BootContext{{}};
    FsFile fp{{&text}};
    {read_context}
    fz::Config config;
    {callback}
    {reader}
    {final}
    sc::Snapshot result;
    result.active = context.is_active;
    result.internal = context.internal_profile;
    result.external = context.external_profile;
    result.profiles = context.profiles;
    return result;
}}
"""


HARNESS_HEAD = r"""
// Generated by tests/test_backend_boot.py. Do not edit this build artifact.
#include "model.hpp"
#include "storage.hpp"
#include "config.hpp"
#include <ini.h>
#include <algorithm>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>

#define R_FAILED(value) ((value) != 0)
constexpr int FsReadOption_None = 0;
struct FsFile { const std::string* text; };
Result fsFileRead(FsFile* file, std::uint64_t offset, void* output,
                  std::uint64_t length, int, std::uint64_t* count) {
    *count = offset >= file->text->size() ? 0 :
        std::min<std::uint64_t>(length, file->text->size() - offset);
    if (*count) std::memcpy(output, file->text->data() + offset, *count);
    return 0;
}

struct BootContext {
    bool is_active = true;
    FizeauProfileId internal_profile = FizeauProfileId_Profile1;
    FizeauProfileId external_profile = FizeauProfileId_Profile1;
    std::array<FizeauProfile, FizeauProfileId_Total> profiles{};
    BootContext() {
        for (auto& profile : profiles) {
            profile.day_settings = profile.night_settings = sc::neutralSettings();
            profile.components = Component_All;
        }
    }
};
BootContext context;

void require(bool condition, const std::string& message) {
    if (!condition) throw std::runtime_error(message);
}

sc::Snapshot desiredSnapshot() {
    sc::Snapshot result;
    result.active = false;
    result.internal = FizeauProfileId_Profile4;
    result.external = FizeauProfileId_Profile3;
    for (unsigned i = 0; i < result.profiles.size(); ++i) {
        auto& profile = result.profiles[i];
        profile.day_settings = profile.night_settings = sc::neutralSettings();
        profile.day_settings.temperature = 7100 + 100 * i;
        profile.night_settings.temperature = 3100 + 100 * i;
        profile.day_settings.saturation = 1.12345678f + 0.01f * i;
        profile.night_settings.saturation = 0.82345678f + 0.01f * i;
        profile.day_settings.hue = -0.1f * (i + 1);
        profile.night_settings.hue = 0.05f * (i + 1);
        profile.day_settings.contrast = 1.01f + 0.1f * i;
        profile.night_settings.contrast = 0.71f + 0.1f * i;
        profile.day_settings.gamma = 1.23f + 0.1f * i;
        profile.night_settings.gamma = 2.34f + 0.1f * i;
        profile.day_settings.luminance = -0.05f * (i + 1);
        profile.night_settings.luminance = 0.03f * (i + 1);
        profile.day_settings.range = {16.0f / 255.0f, 235.0f / 255.0f};
        profile.night_settings.range = {0.01f * (i + 1), 0.99f - 0.01f * i};
        profile.components = static_cast<Component>(i + 1);
        profile.filter = i % 2 ? Component_Red : Component_Blue;
        profile.dusk_begin = {static_cast<std::uint8_t>(18 + i), 15, 0};
        profile.dusk_end = {static_cast<std::uint8_t>(19 + i), 45, 0};
        profile.dawn_begin = {static_cast<std::uint8_t>(4 + i), 10, 0};
        profile.dawn_end = {static_cast<std::uint8_t>(5 + i), 20, 0};
        profile.dimming_timeout = {0, static_cast<std::uint8_t>(i + 1), 37};
    }
    return result;
}
"""

HARNESS_MAIN = r"""
int main() {
    try {
        auto expected = desiredSnapshot();
        std::string text, error;
        require(sc::renderConfig(expected, "", text, error), error);
        const auto original = bootOriginal(text);
        require(original.active == expected.active && original.internal == expected.internal &&
                original.external == expected.external, "Unpatched parser globals did not match");
        for (unsigned i = 0; i < 3; ++i)
            require(sc::sameProfile(original.profiles[i], expected.profiles[i]),
                    "Unpatched parser lost a nonfinal profile: " + std::to_string(i + 1));
        require(!sc::sameProfile(original.profiles[3], expected.profiles[3]),
                "Regression did not reproduce: original parser unexpectedly kept profile4");
        require(sc::sameProfile(original.profiles[3], BootContext{}.profiles[3]),
                "Original final profile was not left at its initial value");
        std::cout << "PASS reproduced: stock Fizeau discards final profile4 at boot\n";
        require(sc::sameSnapshot(bootPatched(text), expected),
                "Patched parser did not round-trip all globals/profiles exactly");
        std::cout << "PASS patched production parser: all globals and 4 complete profiles round-trip\n";

        // Preserved CRLF/comments, aliases, unknown profile keys, and noncanonical
        // section order all pass through the production reader and inih.
        const std::string existing = "; user config\r\nactive=true ; preserve\r\n"
            "[profile4]\r\nfilter_day = none\r\ncustom_key = retained\r\n"
            "[profile2]\r\ncomponents_night = all\r\n";
        expected.active = true;
        expected.internal = FizeauProfileId_Profile2;
        expected.external = FizeauProfileId_Profile4;
        expected.profiles[3].day_settings.saturation = 0.0000000001f;
        require(sc::renderConfig(expected, existing, text, error), error);
        require(sc::sameSnapshot(bootPatched(text), expected),
                "Patched parser lost CRLF/alias/reordered-profile/small-float data");
        std::cout << "PASS production reader: CRLF, comments, aliases, reordered profiles, fixed float notation\n";
        return 0;
    } catch (const std::exception& error) {
        std::cerr << "FAIL backend boot regression: " << error.what() << '\n';
        return 1;
    }
}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bash", type=Path, help="MSYS2 bash.exe on Windows")
    parser.add_argument("--cc", default="gcc")
    parser.add_argument("--cxx", default="g++")
    args = parser.parse_args()
    if not (PATCHED / "sysmodule/src/main.cpp").is_file():
        raise SystemExit("Run scripts/prepare_backend.py before this regression test.")
    original = (UPSTREAM / "sysmodule/src/main.cpp").read_text(encoding="utf-8")
    patched = (PATCHED / "sysmodule/src/main.cpp").read_text(encoding="utf-8")
    if balanced_block(original, FINAL_MARKER) == balanced_block(patched, FINAL_MARKER):
        raise SystemExit("Patched EOF block is identical to upstream; preparation is missing.")
    for path in ("common/src/config_parse.cpp", "lib/inih/inih/ini.c"):
        if (UPSTREAM / path).read_bytes() != (PATCHED / path).read_bytes():
            raise SystemExit(f"Unexpected parser change outside EOF patch: {path}")
    OUT.mkdir(parents=True, exist_ok=True)
    harness = HARNESS_HEAD + boot_function(original, "bootOriginal") + boot_function(patched, "bootPatched") + HARNESS_MAIN
    (OUT / "harness.cpp").write_text(harness, encoding="utf-8")

    def run(command: list[str]) -> None:
        if args.bash:
            # Paths are positional arguments, never interpolated into shell code.
            shell = 'set -e\ncd "$(cygpath -u "$1")"\nshift\n"$@"'
            command = [str(args.bash), "-lc", shell, "switchcolor-boot-test", str(ROOT), *command]
        subprocess.run(command, cwd=ROOT, check=True)

    run([args.cc, "-std=gnu11", "-Wall", "-Wextra", "-Werror", "-DINI_USE_STACK=1", "-c",
         "build/fizeau-backend/lib/inih/inih/ini.c", "-o", "build/backend-boot-test/ini.o"])
    run([args.cxx, "-std=gnu++20", "-Wall", "-Wextra", "-Werror", "-Wno-unused-parameter", "-Wno-implicit-fallthrough",
         "-Wno-missing-field-initializers", "-include", "strings.h",
         "-Itests/stubs", "-Iinclude", "-Ibuild/fizeau-backend/common/include", "-Ibuild/fizeau-backend/lib/inih/include",
         "source/model.cpp", "source/storage.cpp", "build/fizeau-backend/common/src/config_parse.cpp",
         "build/backend-boot-test/harness.cpp", "build/backend-boot-test/ini.o", "-o", "build/backend-boot-test/boot-test.exe"])
    run(["./build/backend-boot-test/boot-test.exe"])


if __name__ == "__main__":
    main()
